<?php

/**
 * ProcessWire HotKey Module
 *
 * Add hot keys to PW admin.
 *
 * 2012/07/17 by Soma Philipp Urlich
 *
 * ProcessWire 2.x
 * Copyright (C) 2010 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class AdminHotKeys extends WireData implements Module, ConfigurableModule {

	protected static $defaults = array(
		'hk_save' => 'ctrl+s',
		'hk_addnew' => 'ctrl+n'
	);

	/**
	 * getModuleInfo is a module required by all modules to tell ProcessWire about them
	 *
	 * @return array
	 *
	 */
	public static function getModuleInfo() {

		return array(
			'title' => 'Hot Keys',
			'version' => 002,
			'summary' => 'Adds hot key functionality in ProcessWire backend. Currently supports: Save, Add New. See jQuery hotkeys plugin at for options [Hotkeys Github](https://github.com/jeresig/jquery.hotkeys)',
			'href' => 'http://processwire.com/talk/topic/1524-admin-hot-keys/',
			'singular' => true,
			'autoload' => true
			);
	}


	public function init() {
		// add js config to admin output
		$config = self::$defaults;
		foreach($config as $key => $unused) $config[$key] = $this->get($key) == null ? $config[$key] : $this->get($key);
		$this->config->js($this->className(), $config);
		// add hook to add scripts
		$this->addHookAfter('Process::execute', $this, 'addHotKeys');
		$this->addHookAfter('Process::executeEdit', $this, 'addHotKeys');
	}

	public function addHotKeys(HookEvent $event) {
		$this->config->scripts->add($this->config->urls->AdminHotKeys . "jquery.hotkeys.js");
		$this->config->scripts->add($this->config->urls->AdminHotKeys . "AdminHotKeys.js");
	}

	static public function getModuleConfigInputfields(array $data) {
		$data = array_merge(self::$defaults, $data);

		$fields = new InputfieldWrapper();
		$modules = wire("modules");

		$field = $modules->get("InputfieldText");
		$field->attr('name', 'hk_save');
		$field->attr('size', 10);
		$field->attr('value', $data['hk_save']);
		$field->label = "Save";
		$field->description = "Enter the hot key to save. Works on all edit screens.";
		$field->notes = "ctrl+s, meta+s, alt+s, shift+s etc.";
		$fields->append($field);

		$field = $modules->get("InputfieldText");
		$field->attr('name', 'hk_addnew');
		$field->attr('size', 10);
		$field->attr('value', $data['hk_addnew']);
		$field->label = "Add New";
		$field->description = "Enter the hot key add new item (Template, Field, User...).";
		$field->notes = "ctrl+n, meta+n, alt+n, shift+n etc.";
		$fields->append($field);

		return $fields;
	}

}
